services:
  datasharing_db:
    image: postgres
    container_name: send_db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - send_data:/var/lib/postgres/data
      - ./backup/backup.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
    environment:
      - POSTGRES_HOST=datasharing_db
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      send_net:
    
  send_backend:
    container_name: datasharing_backend
    image: rallendes/datasharing_backend
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - send_data:/etc/data
      - ./backup/model.json:/etc/data/model.json
    networks:
      send_net:
    depends_on:
      - datasharing_db

  send_enquirer:
    container_name: send_enquirer
    image: rallendes/datasharing_enquirer
    restart: unless-stopped
    ports:
      - 127.0.0.1:4200:80 
    networks:
      send_net:
    depends_on:
      - datasharing_db

volumes:
  send_data:
    name: send_volume

networks:
  send_net:
    driver: bridge